default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: gotocollage_development

test:
  <<: *default
  database: gotocollage_test

production:
  <<: *default
  database: gotocollage_production
  username: gotocollage
  password: <%= ENV['DATABASE_URL'] %>
